# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tabwidgetstacked.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.stackedWidget = QtWidgets.QStackedWidget(Dialog)
        self.stackedWidget.setGeometry(QtCore.QRect(60, 60, 261, 181))
        self.stackedWidget.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"font: 75 8pt \"Nirmala UI\";")
        self.stackedWidget.setObjectName("stackedWidget")
        self.stackedWidgetPage1 = QtWidgets.QWidget()
        self.stackedWidgetPage1.setObjectName("stackedWidgetPage1")
        self.checkBox = QtWidgets.QCheckBox(self.stackedWidgetPage1)
        self.checkBox.setGeometry(QtCore.QRect(10, 40, 241, 20))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.stackedWidgetPage1)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 70, 241, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.stackedWidget.addWidget(self.stackedWidgetPage1)
        self.stackedWidgetPage2 = QtWidgets.QWidget()
        self.stackedWidgetPage2.setObjectName("stackedWidgetPage2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.stackedWidgetPage2)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 40, 81, 20))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.stackedWidgetPage2)
        self.checkBox_4.setGeometry(QtCore.QRect(20, 80, 81, 20))
        self.checkBox_4.setObjectName("checkBox_4")
        self.stackedWidget.addWidget(self.stackedWidgetPage2)
        self.stackedWidgetPage3 = QtWidgets.QWidget()
        self.stackedWidgetPage3.setObjectName("stackedWidgetPage3")
        self.checkBox_5 = QtWidgets.QCheckBox(self.stackedWidgetPage3)
        self.checkBox_5.setGeometry(QtCore.QRect(20, 30, 151, 20))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.stackedWidgetPage3)
        self.checkBox_6.setGeometry(QtCore.QRect(20, 70, 151, 20))
        self.checkBox_6.setObjectName("checkBox_6")
        self.stackedWidget.addWidget(self.stackedWidgetPage3)
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(190, 20, 151, 22))
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 161, 31))
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.checkBox.setText(_translate("Dialog", "Chicken Burger"))
        self.checkBox_2.setText(_translate("Dialog", "Beef Burger"))
        self.checkBox_3.setText(_translate("Dialog", "Coke"))
        self.checkBox_4.setText(_translate("Dialog", "Sprite"))
        self.checkBox_5.setText(_translate("Dialog", "Chocolcate"))
        self.checkBox_6.setText(_translate("Dialog", "Mint"))
        self.label.setText(_translate("Dialog", "Select Category"))
