# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'toolbardemo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 200, 401, 61))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionPlus = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon images/Icons to add to the project/plus.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlus.setIcon(icon)
        self.actionPlus.setObjectName("actionPlus")
        self.actionMinus = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon images/Icons to add to the project/minus.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMinus.setIcon(icon1)
        self.actionMinus.setObjectName("actionMinus")
        self.actionDivide = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon images/Icons to add to the project/divide.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDivide.setIcon(icon2)
        self.actionDivide.setObjectName("actionDivide")
        self.actionMultiply = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon images/Icons to add to the project/multiply.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMultiply.setIcon(icon3)
        self.actionMultiply.setObjectName("actionMultiply")
        self.toolBar.addAction(self.actionPlus)
        self.toolBar.addAction(self.actionMinus)
        self.toolBar.addAction(self.actionDivide)
        self.toolBar.addAction(self.actionMultiply)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionPlus.setText(_translate("MainWindow", "Plus"))
        self.actionPlus.setToolTip(_translate("MainWindow", "Plus"))
        self.actionMinus.setText(_translate("MainWindow", "Minus"))
        self.actionMinus.setToolTip(_translate("MainWindow", "Minus"))
        self.actionDivide.setText(_translate("MainWindow", "Divide"))
        self.actionDivide.setToolTip(_translate("MainWindow", "Divide"))
        self.actionMultiply.setText(_translate("MainWindow", "Multiply"))
        self.actionMultiply.setToolTip(_translate("MainWindow", "Multiply"))
import tmpresource_rc
